-- Q0. Allow a brand to have MORE THAN ONE short domain.
--
-- `short_domains_brand_id_uniq` (migration 0052) enforced exactly one row per
-- brand. That single constraint — not any hardcoded hostname — is what makes the
-- short domain feel fixed: the table, the per-link FK (`links.short_domain_id`)
-- and the redirect are all already domain-agnostic. `app/r/[code]` resolves by
-- the globally-unique short code alone and never reads the Host header, so
-- serving several domains needs no redirect change at all.
--
-- Dropping a UNIQUE INDEX removes a restriction; it does not touch a single row.
-- No column is dropped, no data is rewritten, nothing is deleted. Every existing
-- row and every one of the 3,197,988 links pointing at them are untouched.
--
-- BEHAVIOUR IS UNCHANGED TODAY. The brand→domain pick in lib/sends/kickoff.ts is
-- already deterministic and tolerant of multiple rows:
--     WHERE org_id = … AND brand_id = … AND status = 'active'
--     ORDER BY created_at ASC, id ASC LIMIT 1
-- so with one row per brand it keeps choosing exactly that row. A brand only
-- gains a second domain when an operator deliberately adds one.
--
-- The cross-brand guard `short_domains_org_id_domain_unique (org_id, domain)`
-- STAYS. Two brands must never share a hostname — link attribution is by code,
-- but a shared domain makes the per-brand reporting split meaningless and lets
-- one brand's reputation damage another's deliverability.
--
-- A plain (non-unique) index replaces it so the brand-scoped lookup above keeps
-- an index to use. Not CONCURRENTLY: the table has a single row, so this is
-- instantaneous, and CONCURRENTLY cannot run inside the migration transaction.
DROP INDEX IF EXISTS public.short_domains_brand_id_uniq;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS short_domains_brand_id_idx
  ON public.short_domains (brand_id);
