import { rolePermissions, type Permission, type Role } from "@/lib/permissions";

// Two assertions, and the second one is the reason this file exists.
//
// 1. `operator` equals the access matrix on ClickUp 869et3vm1, literal for
//    literal, IN BOTH DIRECTIONS. Adding a permission to the role without
//    adding it to the matrix here fails — the matrix is a product decision,
//    not something to widen from whichever file you happen to have open.
//
// 2. viewer / manager / admin / owner are UNCHANGED from before Phase 2.
//    This is the load-bearing half. `managerPerms` used to spread
//    `operatorPerms`, so narrowing operator would have silently stripped
//    contacts.upload, opt_outs.upload, lookup.run and ~20 more from manager,
//    admin AND owner — a severe regression inside a change meant to restrict
//    exactly one role. The baselines below were extracted from
//    `git show origin/main:lib/permissions.ts` BEFORE the edit and frozen here,
//    so this compares against something that does not move — not against the
//    file under test (docs/07-conventions.md, "a comparison between two things
//    derived from ONE source proves nothing").

const MATRIX_OPERATOR: Permission[] = [
  // Registry — view only
  "brands.view", "offers.view", "networks.view", "utm_tags.view",
  "routing_types.view", "traffic_types.view", "registry.view",
  // Sending numbers (redacted to a route alias in the response)
  "provider_phones.view",
  // Campaigns & stages — full; delete on stages only (campaigns have no hard
  // delete in this codebase, so "delete a campaign" is archive)
  "campaigns.view", "campaigns.create", "campaigns.update", "campaigns.activate",
  "campaigns.pause", "campaigns.complete", "campaigns.archive", "campaigns.restore",
  "stages.view", "stages.create", "stages.update", "stages.send",
  "stages.archive", "stages.restore", "stages.delete",
  // Creatives — view + create + edit, no archive
  "creatives.view", "creatives.create", "creatives.update",
  // Segments — view + create/edit, counts only
  "segments.view", "segments.create", "segments.update",
  "segment_rules.view", "segment_rules.create", "segment_rules.update",
  "segment_rules.delete",
  // Spam scoring is part of authoring a creative
  "spam.view", "spam.score",
  // May ask for a deletion; only an Owner may approve
  "deletion.request",
];

// Frozen pre-Phase-2 sets. DO NOT regenerate these from lib/permissions.ts —
// that would make the check compare the file against itself.
const FROZEN: Record<Exclude<Role, "operator">, Permission[]> = {
  viewer: [
    "brands.view",
    "campaigns.view",
    "clickers.view",
    "contact_contact_groups.view",
    "contact_groups.view",
    "contacts.view",
    "creatives.view",
    "import_mappings.view",
    "networks.view",
    "offers.view",
    "opt_ins.view",
    "opt_outs.view",
    "provider_phones.view",
    "providers.view",
    "registry.view",
    "result_imports.view",
    "routing_types.view",
    "segment_contacts.view",
    "segment_rules.view",
    "segments.view",
    "spam.view",
    "stages.view",
    "traffic_types.view",
    "utm_tags.view",
  ],
  manager: [
    "brands.archive",
    "brands.create",
    "brands.restore",
    "brands.update",
    "brands.view",
    "campaigns.activate",
    "campaigns.archive",
    "campaigns.complete",
    "campaigns.create",
    "campaigns.drain",
    "campaigns.pause",
    "campaigns.reassign",
    "campaigns.restore",
    "campaigns.update",
    "campaigns.view",
    "clickers.delete",
    "clickers.update",
    "clickers.upload",
    "clickers.view",
    "contact_contact_groups.manage",
    "contact_contact_groups.view",
    "contact_groups.archive",
    "contact_groups.create",
    "contact_groups.restore",
    "contact_groups.update",
    "contact_groups.view",
    "contacts.archive",
    "contacts.delete",
    "contacts.update",
    "contacts.upload",
    "contacts.view",
    "creatives.archive",
    "creatives.create",
    "creatives.restore",
    "creatives.update",
    "creatives.view",
    "import_mappings.create",
    "import_mappings.delete",
    "import_mappings.update",
    "import_mappings.view",
    "lookup.admin",
    "lookup.run",
    "networks.archive",
    "networks.create",
    "networks.restore",
    "networks.update",
    "networks.view",
    "offers.archive",
    "offers.create",
    "offers.restore",
    "offers.update",
    "offers.view",
    "opt_ins.delete",
    "opt_ins.update",
    "opt_ins.upload",
    "opt_ins.view",
    "opt_outs.delete",
    "opt_outs.update",
    "opt_outs.upload",
    "opt_outs.view",
    "partner_keys.view",
    "provider_credentials.view",
    "provider_phones.archive",
    "provider_phones.create",
    "provider_phones.restore",
    "provider_phones.update",
    "provider_phones.view",
    "providers.archive",
    "providers.create",
    "providers.restore",
    "providers.update",
    "providers.view",
    "registry.archive",
    "registry.create",
    "registry.update",
    "registry.view",
    "result_imports.create",
    "result_imports.revert",
    "result_imports.view",
    "routing_types.archive",
    "routing_types.create",
    "routing_types.restore",
    "routing_types.update",
    "routing_types.view",
    "segment_contacts.remove",
    "segment_contacts.upload",
    "segment_contacts.view",
    "segment_rules.create",
    "segment_rules.delete",
    "segment_rules.update",
    "segment_rules.view",
    "segments.archive",
    "segments.create",
    "segments.delete",
    "segments.restore",
    "segments.update",
    "segments.view",
    "spam.score",
    "spam.view",
    "stages.archive",
    "stages.create",
    "stages.delete",
    "stages.restore",
    "stages.send",
    "stages.update",
    "stages.view",
    "traffic_types.archive",
    "traffic_types.create",
    "traffic_types.restore",
    "traffic_types.update",
    "traffic_types.view",
    "utm_tags.archive",
    "utm_tags.create",
    "utm_tags.restore",
    "utm_tags.update",
    "utm_tags.view",
  ],
  admin: [
    "brands.archive",
    "brands.create",
    "brands.restore",
    "brands.update",
    "brands.view",
    "campaigns.activate",
    "campaigns.archive",
    "campaigns.complete",
    "campaigns.create",
    "campaigns.drain",
    "campaigns.pause",
    "campaigns.reassign",
    "campaigns.restore",
    "campaigns.update",
    "campaigns.view",
    "clickers.delete",
    "clickers.update",
    "clickers.upload",
    "clickers.view",
    "contact_contact_groups.manage",
    "contact_contact_groups.view",
    "contact_groups.archive",
    "contact_groups.create",
    "contact_groups.restore",
    "contact_groups.update",
    "contact_groups.view",
    "contacts.archive",
    "contacts.delete",
    "contacts.update",
    "contacts.upload",
    "contacts.view",
    "creatives.archive",
    "creatives.create",
    "creatives.restore",
    "creatives.update",
    "creatives.view",
    "import_mappings.create",
    "import_mappings.delete",
    "import_mappings.update",
    "import_mappings.view",
    "lookup.admin",
    "lookup.run",
    "networks.archive",
    "networks.create",
    "networks.restore",
    "networks.update",
    "networks.view",
    "offers.archive",
    "offers.create",
    "offers.restore",
    "offers.update",
    "offers.view",
    "opt_ins.delete",
    "opt_ins.update",
    "opt_ins.upload",
    "opt_ins.view",
    "opt_outs.delete",
    "opt_outs.update",
    "opt_outs.upload",
    "opt_outs.view",
    "partner_keys.manage",
    "partner_keys.view",
    "provider_credentials.manage",
    "provider_credentials.view",
    "provider_phones.archive",
    "provider_phones.create",
    "provider_phones.restore",
    "provider_phones.update",
    "provider_phones.view",
    "providers.archive",
    "providers.create",
    "providers.restore",
    "providers.update",
    "providers.view",
    "registry.archive",
    "registry.create",
    "registry.update",
    "registry.view",
    "result_imports.create",
    "result_imports.revert",
    "result_imports.view",
    "routing_types.archive",
    "routing_types.create",
    "routing_types.restore",
    "routing_types.update",
    "routing_types.view",
    "segment_contacts.remove",
    "segment_contacts.upload",
    "segment_contacts.view",
    "segment_rules.create",
    "segment_rules.delete",
    "segment_rules.update",
    "segment_rules.view",
    "segments.archive",
    "segments.create",
    "segments.delete",
    "segments.restore",
    "segments.update",
    "segments.view",
    "spam.score",
    "spam.view",
    "stages.archive",
    "stages.create",
    "stages.delete",
    "stages.restore",
    "stages.send",
    "stages.update",
    "stages.view",
    "traffic_types.archive",
    "traffic_types.create",
    "traffic_types.restore",
    "traffic_types.update",
    "traffic_types.view",
    "users.manage",
    "utm_tags.archive",
    "utm_tags.create",
    "utm_tags.restore",
    "utm_tags.update",
    "utm_tags.view",
  ],
  owner: [
    "brands.archive",
    "brands.create",
    "brands.restore",
    "brands.update",
    "brands.view",
    "campaigns.activate",
    "campaigns.archive",
    "campaigns.complete",
    "campaigns.create",
    "campaigns.drain",
    "campaigns.pause",
    "campaigns.reassign",
    "campaigns.restore",
    "campaigns.update",
    "campaigns.view",
    "clickers.delete",
    "clickers.update",
    "clickers.upload",
    "clickers.view",
    "contact_contact_groups.manage",
    "contact_contact_groups.view",
    "contact_groups.archive",
    "contact_groups.create",
    "contact_groups.restore",
    "contact_groups.update",
    "contact_groups.view",
    "contacts.archive",
    "contacts.delete",
    "contacts.update",
    "contacts.upload",
    "contacts.view",
    "creatives.archive",
    "creatives.create",
    "creatives.restore",
    "creatives.update",
    "creatives.view",
    "import_mappings.create",
    "import_mappings.delete",
    "import_mappings.update",
    "import_mappings.view",
    "lookup.admin",
    "lookup.run",
    "networks.archive",
    "networks.create",
    "networks.restore",
    "networks.update",
    "networks.view",
    "offers.archive",
    "offers.create",
    "offers.restore",
    "offers.update",
    "offers.view",
    "opt_ins.delete",
    "opt_ins.update",
    "opt_ins.upload",
    "opt_ins.view",
    "opt_outs.delete",
    "opt_outs.update",
    "opt_outs.upload",
    "opt_outs.view",
    "org.delete",
    "partner_keys.manage",
    "partner_keys.view",
    "provider_credentials.manage",
    "provider_credentials.view",
    "provider_phones.archive",
    "provider_phones.create",
    "provider_phones.restore",
    "provider_phones.update",
    "provider_phones.view",
    "providers.archive",
    "providers.create",
    "providers.restore",
    "providers.update",
    "providers.view",
    "registry.archive",
    "registry.create",
    "registry.update",
    "registry.view",
    "result_imports.create",
    "result_imports.revert",
    "result_imports.view",
    "routing_types.archive",
    "routing_types.create",
    "routing_types.restore",
    "routing_types.update",
    "routing_types.view",
    "segment_contacts.remove",
    "segment_contacts.upload",
    "segment_contacts.view",
    "segment_rules.create",
    "segment_rules.delete",
    "segment_rules.update",
    "segment_rules.view",
    "segments.archive",
    "segments.create",
    "segments.delete",
    "segments.restore",
    "segments.update",
    "segments.view",
    "spam.score",
    "spam.view",
    "stages.archive",
    "stages.create",
    "stages.delete",
    "stages.restore",
    "stages.send",
    "stages.update",
    "stages.view",
    "traffic_types.archive",
    "traffic_types.create",
    "traffic_types.restore",
    "traffic_types.update",
    "traffic_types.view",
    "users.manage",
    "utm_tags.archive",
    "utm_tags.create",
    "utm_tags.restore",
    "utm_tags.update",
    "utm_tags.view",
  ],
};

// Permissions Phase 2 deliberately ADDS to a frozen role, listed explicitly so
// an intentional grant is visible here instead of quietly widening a baseline.
const PHASE2_ADDITIONS: Record<string, Permission[]> = {
  viewer: [],
  manager: ["contacts.export", "campaigns.export", "campaigns.import"],
  admin: ["contacts.export", "campaigns.export", "campaigns.import"],
  owner: [
    "contacts.export", "campaigns.export", "campaigns.import",
    "compliance.manage", "deletion.approve", "audit.view",
  ],
};

let failures = 0;
function check(label: string, ok: boolean, detail: string) {
  console.log("  " + (ok ? "OK " : "XX ") + label + " - " + detail);
  if (!ok) failures++;
}

function diff(a: string[], b: string[]) {
  const bs = new Set(b);
  return a.filter((x) => !bs.has(x));
}

console.log("=== operator permission matrix ===\n");

const live = [...rolePermissions.operator].sort();
const want = [...MATRIX_OPERATOR].sort();
console.log("  scope: live operator set = " + live.length + " permissions, matrix = " + want.length);
if (live.length === 0 || want.length === 0) {
  check("scope", false, "EMPTY - one of the sets did not load");
}

const extra = diff(live, want);
const missing = diff(want, live);
check("operator has nothing beyond the matrix", extra.length === 0,
  extra.length ? "EXTRA: " + extra.join(", ") : "no extras");
check("operator has everything in the matrix", missing.length === 0,
  missing.length ? "MISSING: " + missing.join(", ") : "none missing");

console.log("\n=== other roles unchanged (frozen from origin/main) ===");
console.log("  scope: " + Object.keys(FROZEN).length + " roles");
for (const [role, frozen] of Object.entries(FROZEN)) {
  const expected = [...frozen, ...(PHASE2_ADDITIONS[role] ?? [])].sort();
  const actual = [...rolePermissions[role as Role]].sort();
  const lost = diff(expected, actual);
  const gained = diff(actual, expected);
  check(role + " intact", lost.length === 0 && gained.length === 0,
    lost.length || gained.length
      ? "LOST: [" + lost.join(", ") + "] GAINED: [" + gained.join(", ") + "]"
      : actual.length + " permissions, matches frozen + declared additions");
}

console.log("\n=== " + (failures === 0 ? "ALL PASS" : "FAILURES") + " ===");
process.exit(failures === 0 ? 0 : 1);
